name: Continuous Integration

on: push

jobs:
  install-pipenv:
    name: Install Pipenv
    runs-on: ubuntu-latest

    steps:
      - name: Show current path
        run: pwd

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: current path
        run: pwd
      
      - name: List files
        run: ls

      - name: Install pipenv 
        run: python -m pip install pipenv